### PR TITLE
Ensure string only has numbers before parseFloat

### PR DESCRIPTION
**Pull request by fredevery**

### CODE REVIEW

**Comment by gadicc** [comment]
Hey @fredevery, thanks for the PR and apologies for the 2 month delay.

Can you explain why you needed this?

The regex is too simple, it doesn't handle negative numbers, decimal numbers, Infinity, etc.

But I'm guessing you submitted this to fix something... can you share the specifics so we can cover all use cases?

Thanks.

**Comment by gadicc** [comment]
Useful ref: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/parseFloat

**Comment by threerescuedogsca** [comment]
@gadicc I guess the regex could be swapped out with something like this: /^[-+]?(\d*[.])?\d+$/

**Comment by fredevery** [comment]
@gadicc Essentially what was happening is that data strings that weren't stringified JSON but were actual strings were being parseFloat-ed resulting in a NaN return. So what I was trying to do there was confirm that it was a number before trying to parse it as such. Didn't think about negatives or decimals.

**Comment by fredevery** [comment]
@gadicc I guess the regex could be swapped out with something like this: /^[-+]?(\d*[.])?\d+$/

**Comment by gadicc** [comment]
But NaN can never be returned?

```js
  } else {
    var float = parseFloat(string);
    if (!_.isNaN(float))
      return float;
    return string;
  }
```

Can you give an example of a value that will return a NaN?  It's obviously from somewhere else in the code.

But yes we could probably use regex too.  Still need to cover cases like Infinity.  There's a starting point (unfinished) at https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/parseFloat.

However, this probably isn't where the problem was.

**Comment by gadicc** [comment]
Either way, it's probably not a bad idea to be stricter here.  I modded your regex to use non-capturing groups and match against [+-]?Infinity too.  Thanks :)

**Comment by fredevery** [comment]
Cool. I am not sure why it happened but my debugging did narrow it to that
conditional and when I applied the regex things worked as expected. Nice to know
I can start tracking the package again.

On Wed, May 6, 2015 at 17:16, Gadi Cohen <notifications@github.com> wrote:
Either way, it's probably not a bad idea to be stricter here. I modded your
regex to use non-capturing groups and match against [+-]?Infinity too. Thanks :)

—
Reply to this email directly or view it on GitHub
[https://github.com/gadicc/meteor-famous-views/pull/220#issuecomment-99507765] .[https://github.com/notifications/beacon/AAXdOlaJag9Nh-xHqjpJ6zNJrijNTysoks5oGieygaJpZM4DqRm1.gif]

**Comment by gadicc** [comment]
Yeah I'm sorry for the long delay, busy catching up after needing to prioritize a few other projects.  If you come across this issue again we'll try nip it in the bud :)

**Pull request closed without merging**
